### Creating a logistic regression to predict absenteeism

#### Import relevant librabries

In [1]:
import pandas as pd
import numpy as np

#### Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month_value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

#### Create the targets

In [4]:
# Creating the classes of 'Moderately absent' and 'Excessively absent' by:
## Taking the median value of the 'Absenteesim Time in Hours' and use it as a cut-off mark creating a roughly equal balance

data_preprocessed['Absenteeism Time in Hours'].median()
## So <= 3 is 'Moderately absent' otherwise 'Excessively absent' 
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1,0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month_value  Day of the week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [8]:
# Checking the balance
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
# Creating a checkpoint and dropping the Absenteeism Time in Hours column
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Date',
                                            'Daily Work Load Average', 'Distance to Work',
                                            'Day of the week'],axis=1)

In [10]:
data_with_targets 

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month_value  \
0                 30          0         2     1            7   
1                 31          0         1     0            7   
2                 31          0         0     0            7   
3                 24          0         2     0            7   
4                 30          0         2     1            7   
..               ...        ...       ...   ...          ...   
695               22          1         2     0            5   
696               24          0         1     2            5   
697               25          1         0     0            5   
698               25          1         0     0            5   
699               25          0         1     1            5   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

#### Select the inputs for the regression

In [11]:
data_with_targets.shape

(700, 12)

In [12]:
data_with_targets.iloc[: , :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month_value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

In [13]:
unscaled_inputs =  data_with_targets.iloc[: , :-1]

In [14]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month_value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

#### Standardize the data
absenteesim_scaler would be used to subtract the mean and divide by the standard deviation variablewise

In [15]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [16]:
# import the libraries needed to create the Custom Scaler
# one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling
    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
# check what are all columns that we've got
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month_value'], dtype=object)

In [18]:
# choose the columns to scale
# later augmented this code and put it in comments
#columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [19]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

/Users/fredavictor/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [21]:
absenteeism_scaler.fit(unscaled_inputs)

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs 

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0           0         0         0         1                1.005844 -0.536062   
1           0         0         0         0               -1.574681  2.130803   
2           0         0         0         1               -0.654143  0.248310   
3           1         0         0         0                0.854936  0.405184   
4           0         0         0         1                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695         1         0         0         0               -0.654143  0.562059   
696         1         0         0         0                0.040034 -1.320435   
697         1         0         0         0                1.624567 -1.320435   
698         0         0         0         1                0.190942 -0.692937   
699         0         0         0         1                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets  Month_value  
0           0.767431          0  0.880469  0.268487     0.182726  
1           1.002633          0 -0.019280 -0.589690     0.182726  
2           1.002633          0 -0.919030 -0.589690     0.182726  
3          -0.643782          0  0.880469 -0.589690     0.182726  
4           0.767431          0  0.880469  0.268487     0.182726  
..               ...        ...       ...       ...          ...  
695        -1.114186          1  0.880469 -0.589690    -0.388293  
696        -0.643782          0 -0.019280  1.126663    -0.388293  
697        -0.408580          1 -0.919030 -0.589690    -0.388293  
698        -0.408580          1 -0.919030 -0.589690    -0.388293  
699        -0.408580          0 -0.019280  0.268487    -0.388293  

[700 rows x 11 columns]

In [24]:
scaled_inputs.shape

(700, 11)

#### Split the data into train & test and shuffle

##### Import the relevant module

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
train_test_split(scaled_inputs,targets)

# Splits the dataset to 4 arrays, training and test dataset with inputs and targets

[     Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
 698         0         0         0         1                0.190942 -0.692937   
 514         0         0         0         1                1.036026  0.562059   
 616         0         0         0         1               -0.654143  0.248310   
 438         0         0         0         1               -1.574681  0.091435   
 258         0         0         0         1                0.568211 -0.065439   
 ..        ...       ...       ...       ...                     ...       ...   
 340         0         0         0         1               -0.654143  0.248310   
 176         1         0         0         0               -0.654143 -1.006686   
 162         1         0         0         0                0.387122  1.660180   
 122         0         0         0         1                0.040034 -1.320435   
 242         0         0         0         1               -1.016322 -0.379188   
 
      Body Mas

In [27]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs,targets, train_size = 0.8, random_state = 20)

# train_size as 0.8 means 80% of dataset for training and 20% for test
## random_state gives the shuffle a pseudo random

In [28]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


#### Logistic regression with sklearn

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

##### Training the model

In [30]:
reg = LogisticRegression()

In [31]:
reg.fit(x_train, y_train)

# fits the model according to the given data

LogisticRegression()

In [32]:
# Evaluating the model 
reg.score(x_train, y_train)

# 80% accurate

0.7732142857142857

##### Mannually check the accuracy
Accuracy means that the x% of the model outputs matches the target

In [33]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [34]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
print(np.sum(model_outputs == y_train)) # This is the total number of correct predictions
print(model_outputs.shape[0])# Total obeservation

433
560


In [36]:
np.sum(model_outputs == y_train)/model_outputs.shape[0] # accuracy

0.7732142857142857

#### FInding the intercepts and coefficients

In [37]:
reg.intercept_

array([-1.6474549])

In [38]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.60528415,
        -0.16989096,  0.27981088, -0.21053312,  0.34826214, -0.27739602,
         0.1589299 ]])

#### Creating a summary table to show the intercepts, cofficients and variables

In [39]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month_value'], dtype=object)

In [40]:
# new variable to house the variable names
feature_name = unscaled_inputs.columns.values

In [41]:
summary_table = pd.DataFrame(columns=['Feature_name'],data=feature_name)

In [42]:
# add the coefficients column to match the variable name
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [43]:
summary_table

Feature_name  Coefficient
0                 Reason_1     2.800197
1                 Reason_2     0.951884
2                 Reason_3     3.115553
3                 Reason_4     0.839001
4   Transportation Expense     0.605284
5                      Age    -0.169891
6          Body Mass Index     0.279811
7                Education    -0.210533
8                 Children     0.348262
9                     Pets    -0.277396
10             Month_value     0.158930

In [44]:
summary_table.index = summary_table.index + 1 #shift up all indices by 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]] # Add the intercept to the index 0
summary_table = summary_table.sort_index() # sort table
summary_table

Feature_name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396
11             Month_value     0.158930

#### Interpreting the coefficients 
A feature is not particularly important if:
- if its coefficient is around 0

- if its odds_ratio is around 1

In [45]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [46]:
summary_table

Feature_name  Coefficient  Odds_ratio
0                Intercept    -1.647455    0.192539
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
3                 Reason_3     3.115553   22.545903
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
6                      Age    -0.169891    0.843757
7          Body Mass Index     0.279811    1.322880
8                Education    -0.210533    0.810152
9                 Children     0.348262    1.416604
10                    Pets    -0.277396    0.757754
11             Month_value     0.158930    1.172256

In [47]:
# sort tables to show from most important to least important
summary_table.sort_values('Odds_ratio', ascending=False)

Feature_name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
9                 Children     0.348262    1.416604
7          Body Mass Index     0.279811    1.322880
11             Month_value     0.158930    1.172256
6                      Age    -0.169891    0.843757
8                Education    -0.210533    0.810152
10                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

#### Testing the model

In [48]:
reg.score(x_test, y_test)

0.75

In [49]:
predicted_proba = reg.predict_proba(x_test)

In [50]:
predicted_proba 
predicted_proba.shape

(140, 2)

In [51]:
predicted_proba[:, 1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

#### Save the model
Pickle module to convert a python object into a character stream

In [52]:
import pickle

In [53]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [54]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)